version: '3'

networks:
  sheduledLaraDocker:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: sheduled_lara_docker_nginx
    ports:
      - "8082:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - db
      - redis
    networks:
      - sheduledLaraDocker

  db:
    image: percona
    container_name: sheduled_lara_docker_db
    restart: on-failure
    tty: true
    ports:
      - "3314:3306"
    volumes:
      - ./percona:/var/lib/percona
    environment:
      MYSQL_DATABASE: sheduled_lara_docker_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: qwe123
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    networks:
      - sheduledLaraDocker

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: sheduled_lara_docker_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - sheduledLaraDocker

  composer:
    image: frojd/composer-php-7.4
    container_name: sheduled_lara_docker_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - sheduledLaraDocker

  redis:
    image: redis:alpine
    container_name: sheduled_lara_docker_redis
    volumes:
      - ./redis:/data
    restart: on-failure
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6380:6379
    networks:
      - sheduledLaraDocker

  npm:
    image: node:14.18.0
    container_name: sheduled_lara_docker_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: sheduled_lara_docker_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - sheduledLaraDocker

  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
    container_name: sheduled_lara_docker_cron
    volumes:
      - ./src:/var/www/html
    networks:
      - sheduledLaraDocker
